//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeWork_18_6
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        public Clients(string firstName, string lastName, string middleName,int contactDataId)
        {
            FirstName = firstName;
            LastName = lastName;
            MiddleName = middleName;
            ContactDataID = contactDataId;
        }
        public int ClientID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public int ContactDataID { get; set; }
        public override string ToString()
        {
            return $"{ClientID, 3} {FirstName, 10} {LastName, 10} {MiddleName,10} {ContactDataID , 3}";
        }
    }
}
