//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeWork_18_6
{
    using System;
    using System.Collections.Generic;

    public partial class ContactDatas
    {
        public int ID { get; set; }
        public int TelephonNumber { get; set; }
        public string Email { get; set; }

        public ContactDatas(int telephon, string email)
        {
            TelephonNumber = telephon;
            Email = email;
        }

    }
}
